### ISSUE TITLE
Add book_id to the Reference dataset!

### ISSUE THREAD

**Issue by MasterMedo** [BradyStephenson/bible-data#2]
Although this would duplicate data regarding the Book dataset; this dataset is already superfluous in the mathematical sense.
Adding the book_id would help immensely with inserting data into a graph database.

**Comment by BradyStephenson** [comment]
I aligned column names with the BibleData-Book dataset and changed the book_id to be the unique numeric book identifier (instead of the USX code abbreviation of the book name).  Also added the USX_code to maintain the GEN, EXO, LEV, etc. book name reference.
