### ISSUE TITLE
PersonTimePosition dataset

### ISSUE THREAD

**Issue by MasterMedo** [BradyStephenson/bible-data#4]
This is probably beyond ambitious but it just crossed my mind. Using the Place dataset and reference verses they are mentioned in we can probably deduce who was last seen where and map their journey geographically, but that would require manually parsing the Scripture. If you're interested in such a thing we can try brainstorming how to accomplish it.

**Comment by BradyStephenson** [comment]
YES! :)  It is in the plan.
